moeru-ai/xsai

packages/generate-object/src/index.ts
packages/generate-object/test/__snapshots__/index.test.ts.snap
packages/generate-text/src/index.ts
packages/shared-chat-completion/src/types/chat-completion-options.ts
packages/tool/test/index.test.ts

I use `while` instead of recursion, decreasing the risk of stack overflow.
Meanwhile, I removed chain calling and replaced it with liner code.

feat(generate-text): steps

---

packages/stream-text/src/index.ts

Here, it should not be divided into blocks according to chunks, because sometimes two chunks form a valid block, which should be distinguished according to empty lines.
```ts
for (const line of decoder.decode(chunk).split('\n').filter(line => line))
```
```log
data: {"id":"gen-1734346597
-CmlSiOoSpTCNnoZnoLOP","provider":"OpenAI","model":"openai/gpt-4o-mini","object":"chat.completion.chunk","created":1734346597,"choices":[{"index":0,"delta":{"role":"assistant","content":" connections"},"finish_reason":null,"logprobs":null}],"system_fingerprint":"fp_6fc10e10eb"}
data: {"id":"gen-1734346597-CmlSiOoSpTCNnoZnoLOP","provider":"OpenAI","model":"openai/gpt-4o-mini","object":"chat.completion.chunk","created":1734346597,"choices":[{"index":0,"delta":{"role":"assistant","content":".\n\n"},"finish_re …
```

fix(stream-text): chunk processing

---

packages/shared-chat/src/types/message.ts
packages/shared-chat/src/utils/index.ts
packages/shared-chat/src/utils/message.ts

feat(shared-chat): added message composing heleprs

---

cspell.config.yaml
packages/providers/src/providers/index.ts
packages/providers/src/providers/localai.ts
packages/providers/src/providers/openai-compatible.ts

Can be used with https://localai.io/

feat(providers): add openai-compatible

---

packages/providers/src/providers/google-generative-ai.ts

chore(providers/google-generative-ai): update model list

---

cspell.config.yaml
packages/providers/src/providers/index.ts
packages/providers/src/providers/openrouter.ts
packages/providers/src/types/provider.ts

Reference: [OpenRouter API Reference | Complete API Documentation — OpenRouter | Documentation](https://openrouter.ai/docs/api-reference/overview)

feat(providers): add openrouter

---

cspell.config.yaml
packages/providers/src/providers/deepseek.ts
packages/providers/src/providers/index.ts

Reference: https://api-docs.deepseek.com/quick_start/pricing

feat(providers): add deepseek

---

packages/generate-object/src/index.ts
packages/generate-object/src/jsonSchema.ts
packages/generate-object/test/index.test.ts

- feat: support output option in generate-object

feat(generate-object): support output

---

packages/stream-object/src/index.ts
packages/stream-object/test/index.test.ts

- support array output
- support onFinish
- support elementStream

feat(stream-object): support array output

---

cspell.config.yaml
docs/content/docs/references/meta.json
packages-ext/mcp/package.json
packages-ext/mcp/src/index.ts
packages-ext/mcp/src/sse.ts
packages-ext/mcp/src/stdio.ts
packages-ext/mcp/src/utils/map-tools.ts
packages-ext/mcp/tsup.config.ts
pnpm-lock.yaml
tsconfig.lib.json

feat: new package `@xsai-ext/mcp`

---

CONTRIBUTING.md

docs(contributing): add missing embed model setup

---

packages/generate-text/src/index.ts
packages/generate-text/test/__snapshots__/index.test.ts.snap
packages/shared-chat/src/types/index.ts
packages/shared-chat/src/types/step-type.ts
packages/shared-chat/src/utils/determine-step-type.ts
packages/shared-chat/src/utils/execute-tool.ts
packages/shared-chat/src/utils/index.ts
packages/shared-chat/src/utils/internal/wrap-tool-result.ts
packages/stream-text/src/index.ts

https://github.com/moeru-ai/xsai/pull/102

feat(stream-text): return stepType, finishReason

---

cspell.config.yaml
docs/content/docs/packages/generate/image.mdx
docs/content/docs/packages/generate/meta.json
docs/content/docs/references/meta.json
docs/package.json
eslint.config.ts
packages-top/xsai/package.json
packages-top/xsai/src/index.ts
packages/generate-image/README.md
packages/generate-image/package.json
packages/generate-image/src/index.ts
packages/generate-object/src/index.ts
packages/stream-object/src/index.ts
packages/utils-stream/src/to-async-iterator.ts
pnpm-lock.yaml
pnpm-workspace.yaml

feat: new package `generate-image`

---

packages/generate-text/package.json
packages/generate-text/src/index.ts
packages/shared/src/utils/response-json.ts
pnpm-lock.yaml

- The `res.json()` method may encounter an error.
- The length of the `choices` might be zero.

fix: error handling when return 200

---

docs/content/docs/packages/generate/object.mdx
docs/content/docs/packages/stream/object.mdx
docs/content/docs/packages/tool.mdx

docs: add note for valibot examples

---

docs/content/docs/packages-top/xsschema.mdx
packages-top/xsschema/package.json
packages-top/xsschema/src/to-json-schema/vendors/zod.ts
packages-top/xsschema/test/__snapshots__/to-json-schema.test.ts.snap
packages-top/xsschema/test/to-json-schema.test.ts
pnpm-lock.yaml
pnpm-workspace.yaml

feat(xsschema): support zod 4 beta, zod mini

---

packages/generate-transcription/src/index.ts

reference: https://platform.openai.com/docs/api-reference/audio/createTranscription

feat(generate-transcription): add language, prompt, temperature to request body

---

packages-top/xsschema/package.json
packages-top/xsschema/src/to-json-schema/vendors/index.ts
packages-top/xsschema/src/to-json-schema/vendors/sury.ts
packages-top/xsschema/test/__snapshots__/to-json-schema.test.ts.snap
packages-top/xsschema/test/to-json-schema.test.ts
pnpm-lock.yaml

This is a really nice project. Happy to add Sury to the list:
https://dev.to/dzakh/welcome-sury-the-fastest-schema-with-next-gen-dx-5gl4

feat(xsschema): support sury

---

packages/tool/src/index.ts

fix(tool)!: force strict, set additional properties to false

---

packages/stream-text/src/index.ts

- Improve OpenAI compatibility

fix(stream-text): skip empty choices

---

cspell.config.yaml
packages-ext/providers-local/src/providers/index.ts
packages-ext/providers-local/src/providers/speaches.ts
packages/generate-transcription/test/index.test.ts

feat(providers-local): add speaches

---

cspell.config.yaml
packages/generate-transcription/src/index.ts
packages/generate-transcription/test/__snapshots__/index.test.ts.snap
packages/generate-transcription/test/index.test.ts

feat(generate-transcription): support segments, words

---

packages-ext/providers-local/src/providers/player2.ts

adds a configurable gamekey header for our api, we use this information for metrics (so we know what project the requests are coming from), and to share revenue with creators

add game key as header for player2

---

packages/generate-text/src/index.ts
packages/shared-chat/src/types/message.ts
packages/stream-text/src/index.ts
packages/stream-text/src/internal/_transform-chunk.ts
packages/stream-text/src/types/event.ts

feat: support `reasoning_content`

---

README.md
docs/content/docs/packages/stream/text.mdx
docs/content/docs/packages/utils/reasoning.mdx
docs/content/docs/packages/utils/stream.mdx
packages/stream-object/src/utils/stream-object.ts
packages/stream-text/src/index.ts
packages/stream-text/test/index.test.ts
packages/stream-text/test/tool.test.ts
packages/utils-reasoning/test/qwen3.test.ts

Make `streamText` a sync function that returns the streams and Promises immediately to align with the AI SDK.

refactor(stream-text)!: make to a sync function

---

packages-ext/telemetry/src/index.ts
packages-ext/telemetry/src/utils/now.ts
packages-ext/telemetry/src/utils/record-span.ts
packages-ext/telemetry/src/utils/stream-text-internal.ts
packages-ext/telemetry/src/utils/stream-text.ts
packages-ext/telemetry/test/__snapshots__/stream-text-tools.test.ts.snap
packages-ext/telemetry/test/__snapshots__/stream-text.test.ts.snap
packages-ext/telemetry/test/stream-text-tools.test.ts
packages-ext/telemetry/test/stream-text.test.ts

> This PR is a part of https://github.com/moeru-ai/xsai/pull/212
This PR adds the telemetry support for `streamText`. The skeleton code was copied from `packages/stream-text` to avoid introducing telemetry-originated changes back to that package.

feat: telemetry for stream-text
